# Generated by Django 5.1.4 on 2025-01-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
